[package]
name    = "the-config-user"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
the-default = { path = "{{THE_EDITOR_REPO}}/the-default" }
the-lib     = { path = "{{THE_EDITOR_REPO}}/the-lib" }
