[workspace]
members  = [ "the-dispatch" ]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.metadata.crane]
name = "the-editor"

[workspace.dependencies]
