# Author : Chromo-residuum-opec <development.0extl@simplelogin.com>

"attribute"               = { fg = "green" }
"boolean"                 = { fg = "purple" }
"character"               = { fg = "purple" }
"comment"                 = { fg = "comment_fg" }
"conditional"             = { fg = "blue" }
"constant"                = { fg = "purple" }
"constructor"             = { fg = "blue" }
"diagnostic.deprecated"   = { modifiers = [ "crossed_out" ] }
"diagnostic.error"        = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"         = { underline = { color = "comment_fg", style = "curl" } }
"diagnostic.info"         = { underline = { color = "cyan", style = "curl" } }
"diagnostic.unnecessary"  = { modifiers = [ "dim" ] }
"diagnostic.warning"      = { underline = { color = "orange", style = "curl" } }
"diff.delta"              = { fg = "blue" }
"diff.delta.gutter"       = { bg = "linenr_bg", fg = "cyan" }
"diff.minus"              = { fg = "red" }
"diff.minus.gutter"       = { bg = "linenr_bg", fg = "red" }
"diff.plus"               = { fg = "green" }
"diff.plus.gutter"        = { bg = "linenr_bg", fg = "green" }
"error"                   = { fg = "red" }
"exception"               = { fg = "blue" }
"field"                   = { fg = "background_fg" }
"float"                   = { fg = "purple" }
"function"                = { fg = "pale" }
"function.macro"          = { fg = "green" }
"hint"                    = { fg = "comment_fg" }
"identifier"              = { fg = "blue" }
"info"                    = { fg = "cyan" }
"keyword"                 = { fg = "blue" }
"keyword.directive"       = { fg = "green" }
"keyword.import"          = { fg = "pale" }
"label"                   = { fg = "green" }
"markup.bold"             = { modifiers = [ "bold" ] }
"markup.heading"          = { fg = "blue", modifiers = [ "bold" ] }
"markup.italic"           = { modifiers = [ "italic" ] }
"markup.link"             = { fg = "blue", underline = { style = "line" } }
"markup.link.label"       = { fg = "cyan" }
"markup.link.text"        = { fg = "cyan" }
"markup.link.url"         = { underline = { style = "line" } }
"markup.list"             = { fg = "orange", modifiers = [ "bold" ] }
"markup.raw"              = { fg = "cyan" }
"markup.raw.inline"       = { bg = "black", fg = "blue" }
"markup.strikethrough"    = { modifiers = [ "crossed_out" ] }
"method"                  = { fg = "pale" }
"namespace"               = { fg = "blue" }
"number"                  = { fg = "purple" }
"operator"                = { fg = "blue" }
"parameter"               = { fg = "background_fg" }
"property"                = { fg = "background_fg" }
"punctuation.bracket"     = { fg = "background_fg" }
"punctuation.delimiter"   = { fg = "background_fg" }
"punctuation.special"     = { fg = "green" }
"repeat"                  = { fg = "blue" }
"special"                 = { fg = "green" }
"string"                  = { fg = "cyan" }
"string.escape"           = { fg = "green" }
"string.special"          = { fg = "green" }
"tag"                     = { fg = "blue" }
"tag.attribute"           = { fg = "purple" }
"text"                    = { fg = "background_fg" }
"type"                    = { fg = "blue" }
"ui.background"           = { bg = "background_bg", fg = "background_fg" }
"ui.background.separator" = { fg = "comment_fg" }
"ui.bufferline.active"    = { fg = "pale" }
"ui.cursor.match"         = { bg = "matchparen_bg", fg = "background_fg" }
"ui.cursor.normal"        = { bg = "gray" }
"ui.cursor.primary"       = { modifiers = [ "reversed" ] }
"ui.cursor.select"        = { bg = "gray" }
"ui.cursorline.primary"   = { bg = "linenr_bg" }
"ui.gutter"               = { bg = "linenr_bg", fg = "linenr_fg" }
"ui.help"                 = { bg = "cursorlinenr_bg", fg = "background_fg" }
"ui.linenr"               = { bg = "linenr_bg", fg = "linenr_fg" }
"ui.menu"                 = { bg = "cursorlinenr_bg", fg = "background_fg" }
"ui.menu.border"          = { fg = "comment_fg" }
"ui.menu.selected"        = { bg = "menusel_bg", fg = "menusel_fg" }
"ui.popup"                = { bg = "cursorlinenr_bg", fg = "background_fg" }
"ui.popup.info"           = { fg = "blue" }
"ui.selection"            = { bg = "sel_bg" }
"ui.statusline"           = { bg = "statusline_bg", fg = "statusline_fg" }
"ui.statusline.insert"    = { bg = "blue", fg = "black" }
"ui.statusline.select"    = { bg = "green", fg = "black" }
"ui.text.focus"           = { fg = "orange" }
"ui.virtual"              = { fg = "linenr_fg" }
"ui.virtual.indent-guide" = { fg = "linenr_fg" }
"ui.virtual.jump-label"   = { fg = "orange", modifiers = [ "bold" ] }
"ui.virtual.ruler"        = { bg = "linenr_bg" }
"ui.virtual.whitespace"   = { fg = "sel_bg" }
"ui.window"               = { fg = "comment_fg", modifiers = [ "bold" ] }
"variable"                = { fg = "background_fg" }
"variable.builtin"        = { fg = "blue" }
"warning"                 = { fg = "orange" }

[terminal]
background = "#161822"
foreground = "#c7c9d1"
cursor_color = "#d2d4de"
cursor_text = "#161822"
selection_background = "#282d43"
selection_foreground = "#c7c9d1"
split_divider_color = "#454d73"

  [terminal.palette]
  "0"  = "#1e2132"
  "1"  = "#e27878"
  "2"  = "#b5bf82"
  "3"  = "#e2a478"
  "4"  = "#85a0c7"
  "5"  = "#a093c7"
  "6"  = "#89b9c2"
  "7"  = "#c6c8d1"
  "8"  = "#6b7089"
  "9"  = "#e98989"
  "10" = "#c0ca8e"
  "11" = "#e9b189"
  "12" = "#91acd1"
  "13" = "#ada0d3"
  "14" = "#95c4ce"
  "15" = "#d2d4de"

[palette]

orange = "#e2a578"
pale   = "#a4aecc"
purple = "#a093c8"

black         = "#1e2132"
blue          = "#85a0c7"
cyan          = "#89b9c2"
gray          = "#6b7089"
green         = "#b5bf82"
light-blue    = "#91acd1"
light-cyan    = "#95c4ce"
light-gray    = "#d2d4de"
light-green   = "#c0ca8e"
light-magenta = "#ada0d3"
light-red     = "#e98989"
light-yellow  = "#e9b189"
magenta       = "#a093c7"
red           = "#e27878"
white         = "#c6c8d1"
yellow        = "#e2a478"

background_bg   = "#161822"
background_fg   = "#c7c9d1"
comment_fg      = "#6c7189"
cursorlinenr_bg = "#3d425c"
linenr_bg       = "#1f2233"
linenr_fg       = "#454d73"
matchparen_bg   = "#3f455f"
menusel_bg      = "#5c638a"
menusel_fg      = "#f0f1f5"
sel_bg          = "#282d43"
statusline_bg   = "#0f1117"
statusline_fg   = "#828597"
