[package]
name              = "the-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = [ "staticlib" ]

[dependencies]
ropey.workspace = true
swift-bridge    = "0.1"
the-lib         = { path = "../the-lib" }

[build-dependencies]
swift-bridge-build = "0.1"
