[package]
name    = "the-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
ropey.workspace = true
the-lib = { path = "../the-lib" }
swift-bridge = "0.1"

[build-dependencies]
swift-bridge-build = "0.1"
