[package]
name = "the-default"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
smallvec = "1.13.2"
the-core = { path = "../the-core" }
the-lib = { path = "../the-lib" }
the-dispatch = { path = "../the-dispatch" }

[features]
default = []
cow-handlers = ["the-dispatch/cow-handlers"]
dynamic-registry = ["the-dispatch/dynamic-registry"]
