[package]
name = "the-config"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
the-default = { path = "/Users/misterclayt0n/code/the-editor/the-loader/../the-default" }
the-lib = { path = "/Users/misterclayt0n/code/the-editor/the-loader/../the-lib" }
