[package]
name    = "the-config"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
the-config-user = { package = "the-config-fallback", path = "fallback" }
the-default     = { path = "../the-default" }
