[package]
name              = "the-dispatch"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
paste = "1.0"

[features]
cow-handlers     = [  ]
dynamic-registry = [  ]
editor-hooks     = [  ]
