[package]
name = "the-config-fallback"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
the-default = { path = "../../the-default" }
the-lib     = { path = "../../the-lib" }
